baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "My new Victor-Hugo site"

[[menu.main]]
    url = "/home/"
    name = "Files"
    weight = 6

[[menu.main]]
    url = "/dl/"
    name = "Download"
    weight = 7
	
	
[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
	

[[menu.icon]]
    url = "mailto:info@magejar.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/magejar/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/magejar"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/magejar/"
    name = "instagram"
    weight = 1
	
# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
